version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    groups:
      dependencies:
        patterns:
          - "@pandacss/config"
          - "eslint-plugin-perfectionist"
      dev-dependencies:
        patterns:
          - "@eslint/js"
          - "@types/eslint-config-prettier"
          - "@types/eslint__js"
          - "@types/node"
          - "eslint"
          - "eslint-config-prettier"
          - "prettier"
          - "tsup"
          - "typescript"
          - "typescript-eslint"
